Repository stoplightio/json-schema-viewer, pull requests merged in 2021-04, with the labels that each got.

#124 chore(codeowners): add undefined to CODEOWNERS
  .github/CODEOWNERS
Labels: team/undefined

#130 feat: do not display min/max values for oas formats
  src/utils/__tests__/getValidations.spec.ts
  src/utils/getValidations.ts
Labels: enhancement

#129 fix: use items validation for flattened arrays
  src/__tests__/__snapshots__/index.spec.tsx.snap
  src/tree/utils/walk.ts
Labels: bug

#131 feat: do not display min/max values for oas formats
  src/components/shared/Validations.tsx
  src/components/shared/__tests__/Validations.spec.tsx
Labels: enhancement

#135 feat: special treatment for top level rows
  src/__fixtures__/arrays/of-complex-objects.json
  src/__stories__/JsonSchemaViewer.tsx
  src/__stories__/_styles.scss
  src/__tests__/__snapshots__/index.spec.tsx.snap
  src/__tests__/index.spec.tsx
  src/components/JsonSchemaViewer.tsx
  src/components/SchemaRow/SchemaRow.tsx
  src/components/SchemaRow/TopLevelSchemaRow.tsx
  src/components/SchemaRow/index.ts
  src/components/shared/Caret.tsx
  src/components/shared/ChildStack.tsx
  src/components/shared/__tests__/Property.spec.tsx
  src/consts.ts
Labels: team/undefined

#137 fix: pin mosaic to exact version
  package.json
  src/__tests__/__snapshots__/index.spec.tsx.snap
  src/components/shared/__tests__/Property.spec.tsx
  yarn.lock
Labels: team/undefined

#138 feat: accept JSON Schema Draft 6 & Draft 7
  package.json
  src/components/JsonSchemaViewer.tsx
  src/components/SchemaRow.tsx
  src/components/SchemaTree.tsx
  src/components/shared/Divider.tsx
  src/components/shared/Types.tsx
  src/components/shared/Validations.tsx
  src/tree/__tests__/utils/printTree.ts
  src/tree/metadata.ts
  src/tree/tree.ts
  src/tree/utils/__tests__/walk.spec.ts
  src/tree/utils/canStepIn.ts
  src/tree/utils/mergeAllOf.ts
  src/tree/utils/mergeOneOrAnyOf.ts
  src/tree/utils/populateTree.ts
  src/tree/utils/walk.ts
  src/types.ts
  src/utils/flattenTypes.ts
  src/utils/getAnnotations.ts
  src/utils/getCombiners.ts
  src/utils/getMetadata.ts
  src/utils/getPrimaryType.ts
  src/utils/getValidations.ts
  src/utils/guards.ts
  src/utils/inferType.ts
  src/utils/isCombiner.ts
  src/utils/isValidType.ts
  yarn.lock
Labels: enhancement

#139 feat: accept JSON Schema Draft 6 & Draft 7
  package.json
  src/__tests__/__snapshots__/index.spec.tsx.snap
  src/components/JsonSchemaViewer.tsx
  src/components/shared/Validations.tsx
  src/types.ts
  yarn.lock
Labels: enhancement
